### ISSUE TITLE
User does not have CREATE CATALOG on Metastore 'primary'

### ISSUE THREAD

**Issue by syed-tw** [data-derp/small-exercises#42]
When we try to run CMD 3 of `01-Delta-Lake-Performance`, we get the below error

![Image](https://github.com/data-derp/small-exercises/assets/60807649/feb57683-7634-4b95-94d8-3711ccd457bf)

**Comment by kelseymok** [comment]
@syed-tw permission granted - can you check to see if this works?

**Comment by syed-tw** [comment]
It does not given the Unity Catalog error aymore anymore, but it still says that the Unity catalog is not enabled. Though it has started hive_metastore now as per the below screenshot.
<img width="1057" alt="Screenshot 2023-07-28 at 3 58 17 PM" src="https://github.com/data-derp/small-exercises/assets/60807649/3a244cd6-8351-4a14-be2e-1e95d1a5b78e">

**Comment by kelseymok** [comment]
I've confirmed that the workspace IS connected to the metastore, so it's a little confusing. Perhaps this requires a cluster restart?

**Comment by kelseymok** [comment]
@syed-tw confirmed that this works. Moving to done
